# =============================================================
#   NetScope AI — Phase 7: Anomaly Detection Engine
#   Project: Real-Time Network Traffic Analyzer
# =============================================================
#
#   Builds on:
#
#   Phase 1 → Packet Detection
#   Phase 2 → Packet Inspection
#   Phase 3 → Traffic Statistics
#   Phase 4 → Top Talker Analysis
#   Phase 5 → Port Analysis
#   Phase 6 → Bandwidth Monitor
#
# =============================================================
#
#   NEW IN PHASE 7
#
#   ✅ Network Anomaly Detection
#
#   ✅ High UDP Traffic Alerts
#
#   ✅ High ICMP Traffic Alerts
#
#   ✅ Bandwidth Spike Detection
#
#   ✅ Host Dominance Detection
#
#   ✅ Alert History System
#
#   ✅ Live Threat Monitor
#
# =============================================================
#
#   WHAT IS AN ANOMALY?
#
#   Normal Traffic
#          ↓
#   Unexpected Behavior
#          ↓
#      Anomaly
#
#   Examples:
#
#   • Sudden traffic spike
#   • Too much ICMP traffic
#   • Too much UDP traffic
#   • One device dominating the network
#
# =============================================================
#
#   HOW REAL IDS SYSTEMS WORK
#
#   IDS = Intrusion Detection System
#
#   Examples:
#
#       Snort
#       Suricata
#       Zeek
#
#   They continuously inspect traffic and compare
#   measurements against detection rules.
#
#   Example:
#
#       ICMP > 20%
#
#              ↓
#
#         Generate Alert
#
# =============================================================
#
#   FALSE POSITIVES
#
#   Not every alert means an attack.
#
#   Example:
#
#       You download a game update
#
#       ↓
#
#       Bandwidth spikes
#
#       ↓
#
#       Alert generated
#
#       ↓
#
#       Actually normal behavior
#
# =============================================================

from scapy.all import sniff, IP, TCP, UDP, ICMP

import threading
import time

from datetime import datetime
from collections import Counter


# =============================================================
#   SECTION 1 — PROTOCOL COUNTERS
# =============================================================

counters = {
    "total": 0,
    "tcp": 0,
    "udp": 0,
    "icmp": 0,
    "other": 0,
}


# =============================================================
#   SECTION 2 — TOP TALKER TRACKER
# =============================================================

ip_tracker = Counter()


# =============================================================
#   SECTION 3 — PORT TRACKER
# =============================================================

port_tracker = Counter()


# =============================================================
#   SECTION 4 — COMMON PORT DATABASE
# =============================================================

COMMON_PORTS = {

    20: "FTP-DATA",
    21: "FTP",

    22: "SSH",

    23: "TELNET",

    25: "SMTP",

    53: "DNS",

    67: "DHCP",
    68: "DHCP",

    80: "HTTP",

    110: "POP3",

    123: "NTP",

    143: "IMAP",

    161: "SNMP",

    443: "HTTPS",

    465: "SMTPS",

    587: "SMTP",

    993: "IMAPS",

    995: "POP3S",

    3306: "MYSQL",

    3389: "RDP",

    5432: "POSTGRESQL",

    6379: "REDIS",

    8080: "HTTP-ALT",
}


# =============================================================
#   SECTION 5 — BANDWIDTH TRACKER
# =============================================================

bandwidth = {

    "total_bytes": 0,

    "window_bytes": 0,

    "window_packets": 0,

    "window_start": time.time(),
}


# =============================================================
#   SECTION 6 — ANOMALY DETECTION ENGINE
# =============================================================
#
# alerts
# -------
#
# Stores recent alerts generated by detection rules.
#
# Example:
#
# [
#   "HIGH UDP TRAFFIC",
#   "HIGH ICMP TRAFFIC"
# ]
#
# =============================================================

alerts = []


MAX_ALERTS = 20


# =============================================================
#   DETECTION THRESHOLDS
# =============================================================

UDP_THRESHOLD = 70

ICMP_THRESHOLD = 20

BANDWIDTH_THRESHOLD = 500000

HOST_DOMINANCE_THRESHOLD = 80


# =============================================================
#   SECTION 7 — THREAD LOCK
# =============================================================

lock = threading.Lock()
# =============================================================
#   FUNCTION: analyze_packet(packet)
# =============================================================
#
#   Called by Scapy for EVERY packet captured.
#
#   Responsibilities:
#
#       Phase 3 → Protocol Counters
#
#       Phase 4 → IP Tracking
#
#       Phase 5 → Port Tracking
#
#       Phase 6 → Bandwidth Tracking
#
#       Phase 7 → Supplies data used by
#                 anomaly detection
#
# =============================================================

def analyze_packet(packet):

    if not packet.haslayer(IP):
        return

    ip_layer = packet[IP]

    src_ip = ip_layer.src
    dst_ip = ip_layer.dst

    packet_size = len(packet)

    with lock:

        # =====================================================
        # PROTOCOL COUNTERS
        # =====================================================

        counters["total"] += 1

        if packet.haslayer(TCP):

            counters["tcp"] += 1

        elif packet.haslayer(UDP):

            counters["udp"] += 1

        elif packet.haslayer(ICMP):

            counters["icmp"] += 1

        else:

            counters["other"] += 1

        # =====================================================
        # TOP TALKER ANALYSIS
        # =====================================================

        ip_tracker[src_ip] += 1
        ip_tracker[dst_ip] += 1

        # =====================================================
        # PORT ANALYSIS
        # =====================================================

        if packet.haslayer(TCP):

            tcp_layer = packet[TCP]

            port_tracker[tcp_layer.sport] += 1
            port_tracker[tcp_layer.dport] += 1

        elif packet.haslayer(UDP):

            udp_layer = packet[UDP]

            port_tracker[udp_layer.sport] += 1
            port_tracker[udp_layer.dport] += 1

        # =====================================================
        # BANDWIDTH TRACKING
        # =====================================================

        bandwidth["total_bytes"] += packet_size

        bandwidth["window_bytes"] += packet_size

        bandwidth["window_packets"] += 1


# =============================================================
#   FUNCTION: format_bytes()
# =============================================================
#
#   Converts:
#
#       500
#
#   into:
#
#       500 B
#
#
#       2048
#
#   into:
#
#       2.00 KB
#
# =============================================================

def format_bytes(num_bytes):

    KB = 1024
    MB = 1024 ** 2
    GB = 1024 ** 3

    if num_bytes >= GB:

        return f"{num_bytes / GB:.2f} GB"

    elif num_bytes >= MB:

        return f"{num_bytes / MB:.2f} MB"

    elif num_bytes >= KB:

        return f"{num_bytes / KB:.2f} KB"

    else:

        return f"{int(num_bytes)} B"


# =============================================================
#   FUNCTION: make_bar()
# =============================================================
#
#   Creates proportional visual bars.
#
# =============================================================

def make_bar(count, max_count, bar_width=20):

    if max_count == 0:

        return " " * bar_width

    filled = int(
        (count / max_count) * bar_width
    )

    empty = bar_width - filled

    return (
        "█" * filled
        +
        "░" * empty
    )


# =============================================================
#   FUNCTION: add_alert()
# =============================================================
#
#   Adds alerts safely.
#
#   Keeps only newest MAX_ALERTS entries.
#
# =============================================================

def add_alert(message):

    timestamp = datetime.now().strftime(
        "%H:%M:%S"
    )

    entry = f"[{timestamp}] {message}"

    alerts.append(entry)

    if len(alerts) > MAX_ALERTS:

        alerts.pop(0)


# =============================================================
#   FUNCTION: detect_anomalies()
# =============================================================
#
#   Phase 7 Core Engine
#
# =============================================================
#
#   Detection Rules:
#
#   Rule 1
#       UDP > 70%
#
#   Rule 2
#       ICMP > 20%
#
#   Rule 3
#       Bandwidth > 500 KB/sec
#
#   Rule 4
#       Single Host > 80%
#
# =============================================================

def detect_anomalies(

    total,
    udp,
    icmp,
    bytes_per_sec,
    top_ips

):

    current_alerts = []

    # =========================================================
    # RULE 1
    # HIGH UDP TRAFFIC
    # =========================================================

    if total > 0:

        udp_pct = (
            udp / total
        ) * 100

        if udp_pct > UDP_THRESHOLD:

            message = (
                "HIGH UDP TRAFFIC DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # RULE 2
    # HIGH ICMP TRAFFIC
    # =========================================================

    if total > 0:

        icmp_pct = (
            icmp / total
        ) * 100

        if icmp_pct > ICMP_THRESHOLD:

            message = (
                "HIGH ICMP TRAFFIC DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # RULE 3
    # BANDWIDTH SPIKE
    # =========================================================

    if bytes_per_sec > BANDWIDTH_THRESHOLD:

        message = (
            "BANDWIDTH SPIKE DETECTED"
        )

        current_alerts.append(
            f"⚠ {message}"
        )

    # =========================================================
    # RULE 4
    # HOST DOMINANCE
    # =========================================================

    if top_ips and total > 0:

        top_ip_count = top_ips[0][1]

        host_pct = (
            top_ip_count / total
        ) * 100

        if host_pct > HOST_DOMINANCE_THRESHOLD:

            message = (
                "HOST DOMINANCE DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # STORE ALERT HISTORY
    # =========================================================

    for alert in current_alerts:

        add_alert(alert)

    return current_alerts# =============================================================
#   FUNCTION: print_stats()
# =============================================================
#
#   Central Reporting Engine
#
#   Displays:
#
#       Block 1 → Protocol Statistics
#
#       Block 2 → Top Active IPs
#
#       Block 3 → Top Ports
#
#       Block 4 → Bandwidth Monitor
#
#       Block 5 → Anomaly Detection Engine
#
#       Block 6 → Alert History
#
# =============================================================

def print_stats():

    with lock:

        total = counters["total"]
        tcp = counters["tcp"]
        udp = counters["udp"]
        icmp = counters["icmp"]
        other = counters["other"]

        top_ips = ip_tracker.most_common(10)

        top_ports = port_tracker.most_common(10)

        total_bytes = bandwidth["total_bytes"]

        window_bytes = bandwidth["window_bytes"]

        window_packets = bandwidth["window_packets"]

        window_start = bandwidth["window_start"]

        bandwidth["window_bytes"] = 0

        bandwidth["window_packets"] = 0

        bandwidth["window_start"] = time.time()

    # =========================================================
    # BANDWIDTH CALCULATIONS
    # =========================================================

    now = time.time()

    elapsed = now - window_start

    if elapsed > 0:

        bytes_per_sec = (
            window_bytes / elapsed
        )

        packets_per_sec = (
            window_packets / elapsed
        )

    else:

        bytes_per_sec = 0

        packets_per_sec = 0

    # =========================================================
    # ANOMALY DETECTION
    # =========================================================

    active_alerts = detect_anomalies(

        total,

        udp,

        icmp,

        bytes_per_sec,

        top_ips

    )

    timestamp = datetime.now().strftime(
        "%H:%M:%S"
    )

    def pct(value):

        return (
            value / total * 100
        ) if total > 0 else 0.0

    # =========================================================
    # BLOCK 1
    # PROTOCOL STATISTICS
    # =========================================================

    print("\n" + "═" * 44)

    print(
        "   📊  NETSCOPE AI — LIVE STATISTICS"
    )

    print(
        f"   🕐  Snapshot at : {timestamp}"
    )

    print("═" * 44)

    print(
        f"   Total Packets  : {total}"
    )

    print(
        f"   TCP  Packets   : {tcp:<6} ({pct(tcp):.1f}%)"
    )

    print(
        f"   UDP  Packets   : {udp:<6} ({pct(udp):.1f}%)"
    )

    print(
        f"   ICMP Packets   : {icmp:<6} ({pct(icmp):.1f}%)"
    )

    print(
        f"   Other Packets  : {other:<6} ({pct(other):.1f}%)"
    )

    # =========================================================
    # BLOCK 2
    # TOP TALKERS
    # =========================================================

    print("═" * 44)

    print(
        "   🏆  TOP 10 ACTIVE IP ADDRESSES"
    )

    print("═" * 44)

    if not top_ips:

        print(
            "   ⏳  Waiting for IP traffic..."
        )

    else:

        max_ip_count = top_ips[0][1]

        for rank, (ip, count) in enumerate(
            top_ips,
            start=1
        ):

            bar = make_bar(
                count,
                max_ip_count
            )

            print(
                f"   {rank:<3} "
                f"{ip:<18} "
                f"{bar} "
                f"{count}"
            )

    # =========================================================
    # BLOCK 3
    # TOP PORTS
    # =========================================================

    print("═" * 44)

    print(
        "   🚪  TOP 10 PORTS"
    )

    print("═" * 44)

    if not top_ports:

        print(
            "   ⏳ Waiting for TCP/UDP traffic..."
        )

    else:

        max_port_count = top_ports[0][1]

        for rank, (port, count) in enumerate(
            top_ports,
            start=1
        ):

            service = COMMON_PORTS.get(
                port,
                "UNKNOWN"
            )

            bar = make_bar(
                count,
                max_port_count
            )

            print(
                f"   {rank:<3} "
                f"{port:<6} "
                f"{service:<12} "
                f"{bar} "
                f"{count}"
            )

    # =========================================================
    # BLOCK 4
    # BANDWIDTH MONITOR
    # =========================================================

    print("═" * 44)

    print(
        "   📡  BANDWIDTH MONITOR"
    )

    print("═" * 44)

    print(
        f"   Current Speed  : "
        f"{format_bytes(bytes_per_sec)}/s"
    )

    print(
        f"   Bytes/sec      : "
        f"{bytes_per_sec:,.0f}"
    )

    print(
        f"   Packets/sec    : "
        f"{packets_per_sec:.1f}"
    )

    print(
        f"   Total Data     : "
        f"{format_bytes(total_bytes)}"
    )

    # =========================================================
    # BLOCK 5
    # ANOMALY DETECTION ENGINE
    # =========================================================

    print("═" * 44)

    print(
        "   🚨  ANOMALY DETECTION ENGINE"
    )

    print("═" * 44)

    if active_alerts:

        for alert in active_alerts:

            print(
                f"   {alert}"
            )

    else:

        print(
            "   ✅ No anomalies detected"
        )

    # =========================================================
    # BLOCK 6
    # ALERT HISTORY
    # =========================================================

    print("═" * 44)

    print(
        "   📜  RECENT ALERT HISTORY"
    )

    print("═" * 44)

    if alerts:

        recent = alerts[-5:]

        for entry in recent:

            print(
                f"   {entry}"
            )

    else:

        print(
            "   No alerts generated yet"
        )

    print("═" * 44)

    if total == 0:

        print(
            "   ⏳ No IP packets captured yet"
        )

        print("═" * 44)
        # =============================================================
#   FUNCTION: start_sniffing()
# =============================================================
#
#   Wrapper around Scapy sniff().
#
#   Runs forever inside a daemon thread.
#
# =============================================================

def start_sniffing():

    sniff(
        prn=analyze_packet,
        store=False,
        count=0
    )


# =============================================================
#   MAIN PROGRAM
# =============================================================
#
#   Architecture:
#
#       Thread 1
#       --------
#       Packet Sniffer
#
#       Thread 2
#       --------
#       Statistics Engine
#
# =============================================================

sniffer_thread = threading.Thread(

    target=start_sniffing,

    daemon=True,

    name="PacketSniffer"

)

sniffer_thread.start()


# =============================================================
#   STARTUP BANNER
# =============================================================

print("\n" + "═" * 44)

print(
    "   🚀  NetScope AI — Phase 7 Active"
)

print(
    "   📡  Packet sniffer running"
)

print(
    "   🏆  Top Talkers enabled"
)

print(
    "   🚪  Port Analysis enabled"
)

print(
    "   📊  Bandwidth Monitor enabled"
)

print(
    "   🚨  Anomaly Detection enabled"
)

print(
    "   🔄  Stats refresh every 5 seconds"
)

print(
    "   ⏹   Press Ctrl+C to stop"
)

print("═" * 44)


# =============================================================
#   MAIN LOOP
# =============================================================

try:

    while True:

        time.sleep(5)

        print_stats()


# =============================================================
#   CTRL+C SHUTDOWN
# =============================================================

except KeyboardInterrupt:

    print("\n")

    print(
        "   🛑  Ctrl+C detected"
    )

    print(
        "   📊  Printing final snapshot...\n"
    )

    print_stats()

    print("\n")

    print(
        "   ✅  NetScope AI Phase 7 complete"
    )

    print(
        "   🛡️  Threat Monitoring Engine Active"
    )

    print(
        "   🎯  Ready for Phase 8!"
    )

    print("\n")