# =============================================================
#   NetScope AI — Phase 9: Application Intelligence Engine
#   Project: Real-Time Network Traffic Analyzer
# =============================================================
#
#   Builds on:
#
#   Phase 1 → Packet Detection
#   Phase 2 → Packet Inspection
#   Phase 3 → Traffic Statistics
#   Phase 4 → Top Talker Analysis
#   Phase 5 → Port Analysis
#   Phase 6 → Bandwidth Monitor
#   Phase 7 → Anomaly Detection Engine
#   Phase 8 → Session Intelligence
#
# =============================================================
#
#   NEW IN PHASE 9
#
#   ✅ Application Intelligence Engine
#
#   ✅ Application-Level Traffic Classification
#
#   ✅ Application Activity Tracker
#
#   ✅ Top 10 Application Dashboard
#
#   ✅ Excessive Unknown Traffic Anomaly Rule
#
#   ✅ Visual Application Analytics
#
# =============================================================
#
#   HOW APPLICATION INTELLIGENCE WORKS
#
#   Every packet has a port number.
#
#   Ports map to applications:
#
#       443  → HTTPS
#       80   → HTTP
#       53   → DNS
#       22   → SSH
#       25   → SMTP
#       110  → POP3
#       143  → IMAP
#       123  → NTP
#       67   → DHCP
#       68   → DHCP
#       21   → FTP
#       3306 → MYSQL
#       5432 → POSTGRESQL
#       6379 → REDIS
#
#   If neither the source nor destination port
#   maps to a known application:
#
#       → OTHER
#
#   NetScope AI classifies every TCP/UDP packet
#   and tracks application-level statistics in
#   real time.
#
# =============================================================
#
#   ANOMALY RULE — EXCESSIVE UNKNOWN TRAFFIC
#
#   If OTHER traffic exceeds 30% of total
#   classified application traffic:
#
#       → Generate Alert
#
#   This may indicate:
#
#       • Unrecognized protocols
#       • Custom or proprietary services
#       • Potential tunneling or evasion
#
# =============================================================

from scapy.all import sniff, IP, TCP, UDP, ICMP

import threading
import time

from datetime import datetime
from collections import Counter


# =============================================================
#   SECTION 1 — PROTOCOL COUNTERS
# =============================================================

counters = {
    "total": 0,
    "tcp": 0,
    "udp": 0,
    "icmp": 0,
    "other": 0,
}


# =============================================================
#   SECTION 2 — TOP TALKER TRACKER
# =============================================================

ip_tracker = Counter()


# =============================================================
#   SECTION 3 — PORT TRACKER
# =============================================================

port_tracker = Counter()


# =============================================================
#   SECTION 4 — COMMON PORT DATABASE
# =============================================================

COMMON_PORTS = {

    20: "FTP-DATA",
    21: "FTP",

    22: "SSH",

    23: "TELNET",

    25: "SMTP",

    53: "DNS",

    67: "DHCP",
    68: "DHCP",

    80: "HTTP",

    110: "POP3",

    123: "NTP",

    143: "IMAP",

    161: "SNMP",

    443: "HTTPS",

    465: "SMTPS",

    587: "SMTP",

    993: "IMAPS",

    995: "POP3S",

    3306: "MYSQL",

    3389: "RDP",

    5432: "POSTGRESQL",

    6379: "REDIS",

    8080: "HTTP-ALT",
}


# =============================================================
#   SECTION 5 — BANDWIDTH TRACKER
# =============================================================

bandwidth = {

    "total_bytes": 0,

    "window_bytes": 0,

    "window_packets": 0,

    "window_start": time.time(),
}


# =============================================================
#   SECTION 6 — ANOMALY DETECTION ENGINE
# =============================================================
#
# alerts
# -------
#
# Stores recent alerts generated by detection rules.
#
# Example:
#
# [
#   "HIGH UDP TRAFFIC",
#   "HIGH ICMP TRAFFIC"
# ]
#
# =============================================================

alerts = []


MAX_ALERTS = 20


# =============================================================
#   DETECTION THRESHOLDS
# =============================================================

UDP_THRESHOLD = 70

ICMP_THRESHOLD = 20

BANDWIDTH_THRESHOLD = 500000

HOST_DOMINANCE_THRESHOLD = 80

UNKNOWN_APP_THRESHOLD = 30


# =============================================================
#   SECTION 7 — SESSION TRACKER (PHASE 8)
# =============================================================
#
# A Session represents a communication flow:
#
#   Source IP
#   Destination IP
#   Protocol
#   Source Port
#   Destination Port
#
# Example:
#
#   192.168.1.60
#       →
#   184.86.112.42
#
#   TCP
#   51584 → 443
#
# We store:
#
#   packets
#   bytes
#   first_seen
#   last_seen
#
# =============================================================

session_tracker = {}


# =============================================================
#   SECTION 8 — APPLICATION INTELLIGENCE (PHASE 9)
# =============================================================
#
# Application Tracker
# --------------------
#
# Records application-level activity derived from
# observed TCP/UDP port numbers.
#
# Uses collections.Counter for efficient counting.
#
# Tracked Applications:
#
#   HTTPS, HTTP, DNS, SSH, SMTP, IMAP, POP3,
#   DHCP, NTP, FTP, MYSQL, POSTGRESQL, REDIS,
#   OTHER
#
# =============================================================

app_tracker = Counter()


# =============================================================
#   APPLICATION PORT MAP
# =============================================================
#
# Maps well-known port numbers to application names
# for classification purposes.
#
# If neither src_port nor dst_port matches a known
# application port, the packet is classified as OTHER.
#
# =============================================================

APP_PORT_MAP = {

    443:  "HTTPS",

    80:   "HTTP",

    53:   "DNS",

    22:   "SSH",

    25:   "SMTP",

    110:  "POP3",

    143:  "IMAP",

    123:  "NTP",

    67:   "DHCP",
    68:   "DHCP",

    21:   "FTP",

    3306: "MYSQL",

    5432: "POSTGRESQL",

    6379: "REDIS",
}


# =============================================================
#   HELPER FUNCTION — classify_application()
# =============================================================
#
# Determines the application name for a packet
# based on its source and destination ports.
#
# Priority:
#
#   1. Check destination port first
#   2. Then check source port
#   3. If neither matches → OTHER
#
# =============================================================

def classify_application(src_port, dst_port):

    if dst_port in APP_PORT_MAP:

        return APP_PORT_MAP[dst_port]

    if src_port in APP_PORT_MAP:

        return APP_PORT_MAP[src_port]

    return "OTHER"


# =============================================================
#   HELPER FUNCTION — build_session_key()
# =============================================================
#
# Builds a unique session identifier.
#
# Example:
#
# (
#   "192.168.1.60",
#   "184.86.112.42",
#   "TCP",
#   51584,
#   443
# )
#
# =============================================================

def build_session_key(
    src_ip,
    dst_ip,
    protocol,
    src_port,
    dst_port
):

    return (
        src_ip,
        dst_ip,
        protocol,
        src_port,
        dst_port
    )


# =============================================================
#   SECTION 9 — THREAD LOCK
# =============================================================

lock = threading.Lock()


# =============================================================
#   FUNCTION: analyze_packet(packet)
# =============================================================
#
#   Called by Scapy for EVERY packet captured.
#
#   Responsibilities:
#
#       Phase 3 → Protocol Counters
#
#       Phase 4 → IP Tracking
#
#       Phase 5 → Port Tracking
#
#       Phase 6 → Bandwidth Tracking
#
#       Phase 7 → Supplies data used by
#                 anomaly detection
#
#       Phase 8 → Session Tracking
#
#       Phase 9 → Application Classification
#
# =============================================================

def analyze_packet(packet):

    if not packet.haslayer(IP):
        return

    ip_layer = packet[IP]

    src_ip = ip_layer.src
    dst_ip = ip_layer.dst

    packet_size = len(packet)

    with lock:

        # =====================================================
        # PROTOCOL COUNTERS
        # =====================================================

        counters["total"] += 1

        if packet.haslayer(TCP):

            counters["tcp"] += 1

        elif packet.haslayer(UDP):

            counters["udp"] += 1

        elif packet.haslayer(ICMP):

            counters["icmp"] += 1

        else:

            counters["other"] += 1

        # =====================================================
        # TOP TALKER ANALYSIS
        # =====================================================

        ip_tracker[src_ip] += 1
        ip_tracker[dst_ip] += 1

        # =====================================================
        # PORT ANALYSIS
        # =====================================================

        if packet.haslayer(TCP):

            tcp_layer = packet[TCP]

            port_tracker[tcp_layer.sport] += 1
            port_tracker[tcp_layer.dport] += 1

        elif packet.haslayer(UDP):

            udp_layer = packet[UDP]

            port_tracker[udp_layer.sport] += 1
            port_tracker[udp_layer.dport] += 1

        # =====================================================
        # BANDWIDTH TRACKING
        # =====================================================

        bandwidth["total_bytes"] += packet_size

        bandwidth["window_bytes"] += packet_size

        bandwidth["window_packets"] += 1

        # ======================================================
        # PHASE 8 — SESSION TRACKING
        # ======================================================

        protocol = "OTHER"
        src_port = 0
        dst_port = 0

        if packet.haslayer(TCP):

            protocol = "TCP"

            src_port = packet[TCP].sport
            dst_port = packet[TCP].dport

        elif packet.haslayer(UDP):

            protocol = "UDP"

            src_port = packet[UDP].sport
            dst_port = packet[UDP].dport

        elif packet.haslayer(ICMP):

            protocol = "ICMP"

        session_key = build_session_key(
            src_ip,
            dst_ip,
            protocol,
            src_port,
            dst_port
        )

        current_time = time.time()

        if session_key not in session_tracker:

            session_tracker[session_key] = {

                "packets": 0,
                "bytes": 0,

                "first_seen": current_time,
                "last_seen": current_time

            }

        session_tracker[session_key]["packets"] += 1

        session_tracker[session_key]["bytes"] += packet_size

        session_tracker[session_key]["last_seen"] = current_time

        # ======================================================
        # PHASE 9 — APPLICATION CLASSIFICATION
        # ======================================================
        #
        # For TCP/UDP packets: classify based on ports.
        # For ICMP/OTHER: no application classification
        #   (they have no ports).
        #
        # ======================================================

        if packet.haslayer(TCP) or packet.haslayer(UDP):

            app_name = classify_application(
                src_port,
                dst_port
            )

            app_tracker[app_name] += 1


# =============================================================
#   FUNCTION: format_bytes()
# =============================================================
#
#   Converts:
#
#       500
#
#   into:
#
#       500 B
#
#
#       2048
#
#   into:
#
#       2.00 KB
#
# =============================================================

def format_bytes(num_bytes):

    KB = 1024
    MB = 1024 ** 2
    GB = 1024 ** 3

    if num_bytes >= GB:

        return f"{num_bytes / GB:.2f} GB"

    elif num_bytes >= MB:

        return f"{num_bytes / MB:.2f} MB"

    elif num_bytes >= KB:

        return f"{num_bytes / KB:.2f} KB"

    else:

        return f"{int(num_bytes)} B"


# =============================================================
#   FUNCTION: make_bar()
# =============================================================
#
#   Creates proportional visual bars.
#
# =============================================================

def make_bar(count, max_count, bar_width=20):

    if max_count == 0:

        return " " * bar_width

    filled = int(
        (count / max_count) * bar_width
    )

    empty = bar_width - filled

    return (
        "█" * filled
        +
        "░" * empty
    )


# =============================================================
#   FUNCTION: add_alert()
# =============================================================
#
#   Adds alerts safely.
#
#   Keeps only newest MAX_ALERTS entries.
#
# =============================================================

def add_alert(message):

    timestamp = datetime.now().strftime(
        "%H:%M:%S"
    )

    entry = f"[{timestamp}] {message}"

    alerts.append(entry)

    if len(alerts) > MAX_ALERTS:

        alerts.pop(0)


# =============================================================
#   FUNCTION: detect_anomalies()
# =============================================================
#
#   Phase 7 Core Engine + Phase 9 Extension
#
# =============================================================
#
#   Detection Rules:
#
#   Rule 1
#       UDP > 70%
#
#   Rule 2
#       ICMP > 20%
#
#   Rule 3
#       Bandwidth > 500 KB/sec
#
#   Rule 4
#       Single Host > 80%
#
#   Rule 5 (Phase 9)
#       OTHER application traffic > 30%
#
# =============================================================

def detect_anomalies(

    total,
    udp,
    icmp,
    bytes_per_sec,
    top_ips,
    app_counts

):

    current_alerts = []

    # =========================================================
    # RULE 1
    # HIGH UDP TRAFFIC
    # =========================================================

    if total > 0:

        udp_pct = (
            udp / total
        ) * 100

        if udp_pct > UDP_THRESHOLD:

            message = (
                "HIGH UDP TRAFFIC DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # RULE 2
    # HIGH ICMP TRAFFIC
    # =========================================================

    if total > 0:

        icmp_pct = (
            icmp / total
        ) * 100

        if icmp_pct > ICMP_THRESHOLD:

            message = (
                "HIGH ICMP TRAFFIC DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # RULE 3
    # BANDWIDTH SPIKE
    # =========================================================

    if bytes_per_sec > BANDWIDTH_THRESHOLD:

        message = (
            "BANDWIDTH SPIKE DETECTED"
        )

        current_alerts.append(
            f"⚠ {message}"
        )

    # =========================================================
    # RULE 4
    # HOST DOMINANCE
    # =========================================================

    if top_ips and total > 0:

        top_ip_count = top_ips[0][1]

        host_pct = (
            top_ip_count / total
        ) * 100

        if host_pct > HOST_DOMINANCE_THRESHOLD:

            message = (
                "HOST DOMINANCE DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # RULE 5 (PHASE 9)
    # EXCESSIVE UNKNOWN TRAFFIC
    # =========================================================
    #
    # If OTHER application traffic exceeds 30%
    # of total classified application traffic.
    #
    # =========================================================

    total_app_packets = sum(app_counts.values())

    if total_app_packets > 0:

        other_count = app_counts.get("OTHER", 0)

        other_pct = (
            other_count / total_app_packets
        ) * 100

        if other_pct > UNKNOWN_APP_THRESHOLD:

            message = (
                "EXCESSIVE UNKNOWN TRAFFIC DETECTED"
            )

            current_alerts.append(
                f"⚠ {message}"
            )

    # =========================================================
    # STORE ALERT HISTORY
    # =========================================================

    for alert in current_alerts:

        add_alert(alert)

    return current_alerts


# =============================================================
#   FUNCTION: print_stats()
# =============================================================
#
#   Central Reporting Engine
#
#   Displays:
#
#       Block 1 → Protocol Statistics
#
#       Block 2 → Top Active IPs
#
#       Block 3 → Top Ports
#
#       Block 4 → Bandwidth Monitor
#
#       Block 5 → Top Active Sessions
#
#       Block 6 → Application Intelligence
#
#       Block 7 → Anomaly Detection Engine
#
#       Block 8 → Alert History
#
# =============================================================

def print_stats():

    with lock:

        total = counters["total"]
        tcp = counters["tcp"]
        udp = counters["udp"]
        icmp = counters["icmp"]
        other = counters["other"]

        top_ips = ip_tracker.most_common(10)

        top_ports = port_tracker.most_common(10)

        # ======================================================
        # PHASE 8 — TOP SESSION SNAPSHOT
        # ======================================================

        top_sessions = sorted(

            session_tracker.items(),

            key=lambda item:
                item[1]["packets"],

            reverse=True

        )[:5]

        # ======================================================
        # PHASE 9 — APPLICATION SNAPSHOT
        # ======================================================

        app_counts = dict(app_tracker)

        top_apps = app_tracker.most_common(10)

        total_bytes = bandwidth["total_bytes"]

        window_bytes = bandwidth["window_bytes"]

        window_packets = bandwidth["window_packets"]

        window_start = bandwidth["window_start"]

        bandwidth["window_bytes"] = 0

        bandwidth["window_packets"] = 0

        bandwidth["window_start"] = time.time()

    # =========================================================
    # BANDWIDTH CALCULATIONS
    # =========================================================

    now = time.time()

    elapsed = now - window_start

    if elapsed > 0:

        bytes_per_sec = (
            window_bytes / elapsed
        )

        packets_per_sec = (
            window_packets / elapsed
        )

    else:

        bytes_per_sec = 0

        packets_per_sec = 0

    # =========================================================
    # ANOMALY DETECTION
    # =========================================================

    active_alerts = detect_anomalies(

        total,

        udp,

        icmp,

        bytes_per_sec,

        top_ips,

        app_counts

    )

    timestamp = datetime.now().strftime(
        "%H:%M:%S"
    )

    def pct(value):

        return (
            value / total * 100
        ) if total > 0 else 0.0

    # =========================================================
    # BLOCK 1
    # PROTOCOL STATISTICS
    # =========================================================

    print("\n" + "═" * 44)

    print(
        "   📊  NETSCOPE AI — LIVE STATISTICS"
    )

    print(
        f"   🕐  Snapshot at : {timestamp}"
    )

    print("═" * 44)

    print(
        f"   Total Packets  : {total}"
    )

    print(
        f"   TCP  Packets   : {tcp:<6} ({pct(tcp):.1f}%)"
    )

    print(
        f"   UDP  Packets   : {udp:<6} ({pct(udp):.1f}%)"
    )

    print(
        f"   ICMP Packets   : {icmp:<6} ({pct(icmp):.1f}%)"
    )

    print(
        f"   Other Packets  : {other:<6} ({pct(other):.1f}%)"
    )

    # =========================================================
    # BLOCK 2
    # TOP TALKERS
    # =========================================================

    print("═" * 44)

    print(
        "   🏆  TOP 10 ACTIVE IP ADDRESSES"
    )

    print("═" * 44)

    if not top_ips:

        print(
            "   ⏳  Waiting for IP traffic..."
        )

    else:

        max_ip_count = top_ips[0][1]

        for rank, (ip, count) in enumerate(
            top_ips,
            start=1
        ):

            bar = make_bar(
                count,
                max_ip_count
            )

            print(
                f"   {rank:<3} "
                f"{ip:<18} "
                f"{bar} "
                f"{count}"
            )

    # =========================================================
    # BLOCK 3
    # TOP PORTS
    # =========================================================

    print("═" * 44)

    print(
        "   🚪  TOP 10 PORTS"
    )

    print("═" * 44)

    if not top_ports:

        print(
            "   ⏳ Waiting for TCP/UDP traffic..."
        )

    else:

        max_port_count = top_ports[0][1]

        for rank, (port, count) in enumerate(
            top_ports,
            start=1
        ):

            service = COMMON_PORTS.get(
                port,
                "UNKNOWN"
            )

            bar = make_bar(
                count,
                max_port_count
            )

            print(
                f"   {rank:<3} "
                f"{port:<6} "
                f"{service:<12} "
                f"{bar} "
                f"{count}"
            )

    # =========================================================
    # BLOCK 4
    # BANDWIDTH MONITOR
    # =========================================================

    print("═" * 44)

    print(
        "   📡  BANDWIDTH MONITOR"
    )

    print("═" * 44)

    print(
        f"   Current Speed  : "
        f"{format_bytes(bytes_per_sec)}/s"
    )

    print(
        f"   Bytes/sec      : "
        f"{bytes_per_sec:,.0f}"
    )

    print(
        f"   Packets/sec    : "
        f"{packets_per_sec:.1f}"
    )

    print(
        f"   Total Data     : "
        f"{format_bytes(total_bytes)}"
    )

    # ==========================================================
    # BLOCK 5
    # TOP ACTIVE SESSIONS (PHASE 8)
    # ==========================================================

    print("═" * 44)
    print("   🔗  TOP ACTIVE SESSIONS")
    print("═" * 44)

    if not top_sessions:

        print("   ⏳  No active sessions yet.")

    else:

        for session_key, data in top_sessions:

            (
                src_ip,
                dst_ip,
                protocol,
                src_port,
                dst_port
            ) = session_key

            duration = (
                data["last_seen"]
                -
                data["first_seen"]
            )

            print()

            print(
                f"   {src_ip}"
            )

            print(
                f"      → {dst_ip}"
            )

            print()

            print(
                f"   {protocol}"
            )

            print(
                f"   {src_port} → {dst_port}"
            )

            print()

            print(
                f"   Packets  : "
                f"{data['packets']}"
            )

            print(
                f"   Bytes    : "
                f"{format_bytes(data['bytes'])}"
            )

            print(
                f"   Duration : "
                f"{duration:.1f} sec"
            )

            print()

            print(
                "   " + "─" * 32
            )

    print("═" * 44)

    # ==========================================================
    # BLOCK 6
    # APPLICATION INTELLIGENCE (PHASE 9)
    # ==========================================================

    print("═" * 44)

    print(
        "   🧠  APPLICATION INTELLIGENCE"
    )

    print("═" * 44)

    total_app_packets = sum(
        app_counts.values()
    )

    if not top_apps:

        print(
            "   ⏳  Waiting for application traffic..."
        )

    else:

        max_app_count = top_apps[0][1]

        for rank, (app_name, count) in enumerate(
            top_apps,
            start=1
        ):

            if total_app_packets > 0:

                app_pct = (
                    count / total_app_packets
                ) * 100

            else:

                app_pct = 0.0

            bar = make_bar(
                count,
                max_app_count
            )

            print(
                f"   {rank:<3} "
                f"{app_name:<14} "
                f"{bar} "
                f"{count:<6} "
                f"{app_pct:5.1f}%"
            )

    print("═" * 44)

    # =========================================================
    # BLOCK 7
    # ANOMALY DETECTION ENGINE
    # =========================================================

    print("═" * 44)

    print(
        "   🚨  ANOMALY DETECTION ENGINE"
    )

    print("═" * 44)

    if active_alerts:

        for alert in active_alerts:

            print(
                f"   {alert}"
            )

    else:

        print(
            "   ✅ No anomalies detected"
        )

    # =========================================================
    # BLOCK 8
    # ALERT HISTORY
    # =========================================================

    print("═" * 44)

    print(
        "   📜  RECENT ALERT HISTORY"
    )

    print("═" * 44)

    if alerts:

        recent = alerts[-5:]

        for entry in recent:

            print(
                f"   {entry}"
            )

    else:

        print(
            "   No alerts generated yet"
        )

    print("═" * 44)

    if total == 0:

        print(
            "   ⏳ No IP packets captured yet"
        )

        print("═" * 44)


# =============================================================
#   FUNCTION: start_sniffing()
# =============================================================
#
#   Wrapper around Scapy sniff().
#
#   Runs forever inside a daemon thread.
#
# =============================================================

def start_sniffing():

    sniff(
        prn=analyze_packet,
        store=False,
        count=0
    )


# =============================================================
#   MAIN PROGRAM
# =============================================================
#
#   Architecture:
#
#       Thread 1
#       --------
#       Packet Sniffer
#
#       Thread 2
#       --------
#       Statistics Engine
#
# =============================================================

sniffer_thread = threading.Thread(

    target=start_sniffing,

    daemon=True,

    name="PacketSniffer"

)

sniffer_thread.start()


# =============================================================
#   STARTUP BANNER
# =============================================================

print("\n" + "═" * 44)

print(
    "   🚀  NetScope AI — Phase 9 Active"
)

print(
    "   📡  Packet sniffer running"
)

print(
    "   🏆  Top Talkers enabled"
)

print(
    "   🚪  Port Analysis enabled"
)

print(
    "   📊  Bandwidth Monitor enabled"
)

print(
    "   🚨  Anomaly Detection enabled"
)

print(
    "   🔗  Session Intelligence enabled"
)

print(
    "   🧠  Application Intelligence enabled"
)

print(
    "   🔄  Stats refresh every 5 seconds"
)

print(
    "   ⏹   Press Ctrl+C to stop"
)

print("═" * 44)


# =============================================================
#   MAIN LOOP
# =============================================================

try:

    while True:

        time.sleep(5)

        print_stats()


# =============================================================
#   CTRL+C SHUTDOWN
# =============================================================

except KeyboardInterrupt:

    print("\n")

    print(
        "   🛑  Ctrl+C detected"
    )

    print(
        "   📊  Printing final snapshot...\n"
    )

    print_stats()

    print("\n")

    print(
        "   ✅  NetScope AI Phase 9 complete"
    )

    print(
        "   🧠  Application Intelligence Engine Active"
    )

    print(
        "   🎯  Ready for Phase 10!"
    )

    print("\n")
